//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sample_6_6.Properties {
  using System;


  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Resources {

    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Resources() {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("sample_6_6.Properties.Resources", typeof(Resources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage _event {
      get {
        object obj = ResourceManager.GetObject("event", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage customers {
      get {
        object obj = ResourceManager.GetObject("customers", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage dashboard {
      get {
        object obj = ResourceManager.GetObject("dashboard", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage discardchanges {
      get {
        object obj = ResourceManager.GetObject("discardchanges", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage pivotoverview {
      get {
        object obj = ResourceManager.GetObject("pivotoverview", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage printexport {
      get {
        object obj = ResourceManager.GetObject("printexport", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage report {
      get {
        object obj = ResourceManager.GetObject("report", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage roombooking_alt {
      get {
        object obj = ResourceManager.GetObject("roombooking-alt", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage savechanges {
      get {
        object obj = ResourceManager.GetObject("savechanges", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }

    /// <summary>
    ///   Looks up a localized resource of type DevExpress.Utils.Svg.SvgImage.
    /// </summary>
    internal static DevExpress.Utils.Svg.SvgImage venue {
      get {
        object obj = ResourceManager.GetObject("venue", resourceCulture);
        return ((DevExpress.Utils.Svg.SvgImage)(obj));
      }
    }
  }
}
